# Generated by Django 3.0.3 on 2020-02-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0002_auto_20200220_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(default='PK', max_length=2, unique=True),
        ),
    ]
